spring:
  application:
    name: webflux-sample
  main:
    banner-mode: off
  profiles:
    active: dev

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: warn
